apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
  namespace: flix
data:
  PORT: "3004"
  ELASTICSEARCH_URL: "http://eswrapper:9200"
  REDIS_URL: "redis://redis:6379"
  CATALOG_SERVICE_URL: "http://catalog-service:3002"
  LOG_LEVEL: "info"
