apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-service-config
  namespace: flix
data:
  PORT: "3003"
  MONGODB_URI: "mongodb://mongodb:27017/flixstream_recommendations"
  REDIS_URL: "redis://redis:6379"
  CATALOG_SERVICE_URL: "http://catalog-service:3002"
  USER_SERVICE_URL: "http://user-service:3001"
  LOG_LEVEL: "info"
