apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-gateway-rollout.yaml
  - user-service-rollout.yaml
  - catalog-service-rollout.yaml
  - recommendation-service-rollout.yaml
  - search-service-rollout.yaml
  - payment-service-rollout.yaml
  - frontend-rollout.yaml
