apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "8080"
  GIN_MODE: "release"
  USER_SERVICE_URL: "http://prod-user-service:3001"
  CATALOG_SERVICE_URL: "http://prod-catalog-service:3002"
  RECOMMENDATION_SERVICE_URL: "http://prod-recommendation-service:3003"
  SEARCH_SERVICE_URL: "http://prod-search-service:3005"
  PAYMENT_SERVICE_URL: "http://prod-payment-service:3006"
  ALLOWED_ORIGINS: "https://flixstream.com,https://www.flixstream.com"
