apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
data:
  PORT: "3002"
  NODE_ENV: "production"
  MONGODB_URI: "mongodb://prod-mongodb:27017/flixstream_catalog"
  REDIS_URL: "redis://prod-redis:6379"
  USER_SERVICE_URL: "http://prod-user-service:3001"
  ALLOWED_ORIGINS: "https://flixstream.com,https://www.flixstream.com"
