apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: flix
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: flix
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: flix
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: flix
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: flix
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: flix
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: flix
$patch: delete
