# Remove only the Deployments that are being replaced by Rollouts
# Currently only catalog-service is active
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: flix
$patch: delete
