apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # API Gateway
  - api-gateway-rollout.yaml
  - api-gateway-preview-service.yaml
  # User Service
  - user-service-rollout.yaml
  - user-service-preview-service.yaml
  # Catalog Service
  - catalog-service-rollout.yaml
  - catalog-service-preview-service.yaml
  # Recommendation Service
  - recommendation-service-rollout.yaml
  - recommendation-service-preview-service.yaml
  # Search Service
  - search-service-rollout.yaml
  - search-service-preview-service.yaml
  # Payment Service
  - payment-service-rollout.yaml
  - payment-service-preview-service.yaml
  # Frontend
  - frontend-rollout.yaml
  - frontend-preview-service.yaml
