apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: flix
data:
  APP_PORT: "3001"
  MONGO_URI: "mongodb://mongodb:27017/flixstream"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  ELASTICSEARCH_URL: "http://eswrapper:9200"
