apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: flix
data:
  PORT: "3001"
  MONGODB_URI: "mongodb://mongodb:27017/flixstream_users"
  REDIS_URL: "redis://redis:6379"
  JWT_SECRET: "flixstream-jwt-secret"
  LOG_LEVEL: "info"
