apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: flix
data:
  PORT: "3006"
  MONGODB_URI: "mongodb://mongodb:27017/flixstream_payments"
  USER_SERVICE_URL: "http://user-service:3001"
  FRONTEND_URL: "http://localhost:5173"
  MIDTRANS_IS_PRODUCTION: "false"
