apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "8080"
  NODE_ENV: "rolling"
  USER_SERVICE_URL: "http://rolling-user-service:3001"
  CATALOG_SERVICE_URL: "http://rolling-catalog-service:3002"
  RECOMMENDATION_SERVICE_URL: "http://rolling-recommendation-service:3003"
  SEARCH_SERVICE_URL: "http://rolling-search-service:3004"
  PAYMENT_SERVICE_URL: "http://rolling-payment-service:3005"
  LOG_LEVEL: "info"
  ALLOWED_ORIGINS: "http://rolling-frontend:3000,http://localhost:3000"
