apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: "3005"
  NODE_ENV: "rolling"
  MONGODB_URI: "mongodb://rolling-mongodb:27017/flixstream_payments_rolling"
  REDIS_URL: "redis://rolling-redis:6379"
  RABBITMQ_URL: "amqp://rolling-rabbitmq:5672"
  USER_SERVICE_URL: "http://rolling-user-service:3001"
  LOG_LEVEL: "info"
