apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-service-config
data:
  PORT: "3003"
  NODE_ENV: "rolling"
  MONGODB_URI: "mongodb://rolling-mongodb:27017/flixstream_recommendations_rolling"
  REDIS_URL: "redis://rolling-redis:6379"
  CATALOG_SERVICE_URL: "http://rolling-catalog-service:3002"
  USER_SERVICE_URL: "http://rolling-user-service:3001"
  LOG_LEVEL: "info"
