apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  PORT: "3001"
  NODE_ENV: "rolling"
  MONGODB_URI: "mongodb://rolling-mongodb:27017/flixstream_users_rolling"
  REDIS_URL: "redis://rolling-redis:6379"
  JWT_SECRET: "flixstream-jwt-secret-rolling"
  LOG_LEVEL: "info"
  ALLOWED_ORIGINS: "http://rolling-frontend:3000,http://localhost:3000"
