apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "8080"
  NODE_ENV: "bluegreen"
  USER_SERVICE_URL: "http://bluegreen-user-service:3001"
  CATALOG_SERVICE_URL: "http://bluegreen-catalog-service:3002"
  RECOMMENDATION_SERVICE_URL: "http://bluegreen-recommendation-service:3003"
  SEARCH_SERVICE_URL: "http://bluegreen-search-service:3004"
  PAYMENT_SERVICE_URL: "http://bluegreen-payment-service:3005"
  LOG_LEVEL: "info"
  ALLOWED_ORIGINS: "http://bluegreen-frontend:3000,https://flixstream.com"
