apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
data:
  PORT: "3002"
  NODE_ENV: "bluegreen"
  MONGODB_URI: "mongodb://bluegreen-mongodb:27017/flixstream_catalog_bluegreen"
  REDIS_URL: "redis://bluegreen-redis:6379"
  USER_SERVICE_URL: "http://bluegreen-user-service:3001"
  LOG_LEVEL: "info"
  ALLOWED_ORIGINS: "http://bluegreen-frontend:3000,https://flixstream.com"
