apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: "3005"
  NODE_ENV: "bluegreen"
  MONGODB_URI: "mongodb://bluegreen-mongodb:27017/flixstream_payments_bluegreen"
  REDIS_URL: "redis://bluegreen-redis:6379"
  RABBITMQ_URL: "amqp://bluegreen-rabbitmq:5672"
  USER_SERVICE_URL: "http://bluegreen-user-service:3001"
  LOG_LEVEL: "info"
