apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-service-config
data:
  PORT: "3003"
  NODE_ENV: "bluegreen"
  MONGODB_URI: "mongodb://bluegreen-mongodb:27017/flixstream_recommendations_bluegreen"
  REDIS_URL: "redis://bluegreen-redis:6379"
  CATALOG_SERVICE_URL: "http://bluegreen-catalog-service:3002"
  USER_SERVICE_URL: "http://bluegreen-user-service:3001"
  LOG_LEVEL: "info"
