apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "8080"
  GIN_MODE: "debug"
  USER_SERVICE_URL: "http://dev-user-service:3001"
  CATALOG_SERVICE_URL: "http://dev-catalog-service:3002"
  RECOMMENDATION_SERVICE_URL: "http://dev-recommendation-service:3003"
  SEARCH_SERVICE_URL: "http://dev-search-service:3005"
  PAYMENT_SERVICE_URL: "http://dev-payment-service:3006"
  ALLOWED_ORIGINS: "http://dev-frontend:80,http://localhost:3000,http://localhost:8080,http://localhost:5173"
