apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
data:
  PORT: "3002"
  NODE_ENV: "development"
  MONGODB_URI: "mongodb://dev-mongodb-0.dev-mongodb.flix-dev.svc.cluster.local:27017/flixstream_payments_dev"
  REDIS_URL: "redis://dev-redis:6379"
  USER_SERVICE_URL: "http://dev-user-service:3001"
  ALLOWED_ORIGINS: "http://dev-frontend:80,http://localhost:3000,http://localhost:8080,http://localhost:5173"
