apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_APP_NAME: "FlixStream Dev"
  VITE_AUTH_API_BASE: "http://dev-user-service:3001/api/auth"
  VITE_CATALOG_API_BASE: "http://dev-catalog-service:3002"
  VITE_RECOMMENDATION_API_BASE: "http://dev-recommendation-service:3003/api/recommendations"
  VITE_SEARCH_API_BASE: "http://dev-search-service:3005/api/search"
  VITE_PAYMENT_API_BASE: "http://dev-payment-service:3006/api/payments"
