apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: "3006"
  NODE_ENV: "development"
  MONGODB_URI: "mongodb://dev-mongodb.flix-dev.svc.cluster.local:27017/flixstream_payments_dev"
  USER_SERVICE_URL: "http://dev-user-service:3001"
  FRONTEND_URL: "http://dev-frontend:80"
  REDIS_URL: "redis://dev-redis:6379"
  ALLOWED_ORIGINS: "http://dev-frontend:80,http://localhost:3000,http://localhost:8080,http://localhost:5173"
  MIDTRANS_IS_PRODUCTION: "false"
