apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-service-config
data:
  PORT: "3003"
  NODE_ENV: "development"
  MONGODB_URI: "mongodb://dev-mongodb.flix-dev.svc.cluster.local:27017/flixstream_recommendations_dev"
  REDIS_URL: "redis://dev-redis:6379"
  RABBITMQ_URL: "amqp://guest:guest@dev-rabbitmq:5672/"
  CATALOG_SERVICE_URL: "http://dev-catalog-service:3002"
  USER_SERVICE_URL: "http://dev-user-service:3001"
