apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  APP_PORT: "3001"
  NODE_ENV: "dev"
  MONGODB_URI: "mongodb://dev-mongodb.flix-dev.svc.cluster.local:27017/flixstream-dev"
  REDIS_HOST: "dev-redis"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://dev-redis:6379"
  RABBITMQ_URL: "amqp://guest:guest@dev-rabbitmq:5672/"
  ELASTICSEARCH_URL: "http://dev-eswrapper:9200"
