apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
  namespace: flix
data:
  PORT: "3002"
  MONGODB_URI: "mongodb://mongodb:27017/flixstream_catalog"
  REDIS_URL: "redis://redis:6379"
  USER_SERVICE_URL: "http://user-service:3001"
