apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
data:
  PORT: "3002"
  NODE_ENV: "staging"
  MONGODB_URI: "mongodb://staging-mongodb:27017/flixstream_catalog_staging"
  REDIS_URL: "redis://staging-redis:6379"
  USER_SERVICE_URL: "http://staging-user-service:3001"
  ALLOWED_ORIGINS: "https://staging.flixstream.com"
