# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api-gateway
#   namespace: flix
# spec:
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 1
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: user-service
#   namespace: flix
# spec:
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 1
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: flix
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: recommendation-service
#   namespace: flix
# spec:
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 1
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: search-service
#   namespace: flix
# spec:
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 1
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: payment-service
#   namespace: flix
# spec:
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 1
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend
#   namespace: flix
# spec:
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 1
