apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: flix
data:
  PORT: "8080"
  GIN_MODE: "release"
  USER_SERVICE_URL: "http://user-service:3001"
  CATALOG_SERVICE_URL: "http://catalog-service:3002"
  RECOMMENDATION_SERVICE_URL: "http://recommendation-service:3003"
  SEARCH_SERVICE_URL: "http://search-service:3005"
  PAYMENT_SERVICE_URL: "http://payment-service:3006"
  ALLOWED_ORIGINS: "*"
