apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "8080"
  NODE_ENV: "manual"
  USER_SERVICE_URL: "http://manual-user-service:3001"
  CATALOG_SERVICE_URL: "http://manual-catalog-service:3002"
  RECOMMENDATION_SERVICE_URL: "http://manual-recommendation-service:3003"
  SEARCH_SERVICE_URL: "http://manual-search-service:3004"
  PAYMENT_SERVICE_URL: "http://manual-payment-service:3005"
  LOG_LEVEL: "debug"
  ALLOWED_ORIGINS: "http://manual-frontend:3000,http://localhost:3000,http://localhost:8080"
