apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-service-config
data:
  PORT: "3002"
  NODE_ENV: "manual"
  MONGODB_URI: "mongodb://manual-mongodb:27017/flixstream_catalog_manual"
  REDIS_URL: "redis://manual-redis:6379"
  USER_SERVICE_URL: "http://manual-user-service:3001"
  LOG_LEVEL: "debug"
  ALLOWED_ORIGINS: "http://manual-frontend:3000,http://localhost:3000"
