apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PORT: "3005"
  NODE_ENV: "manual"
  MONGODB_URI: "mongodb://manual-mongodb:27017/flixstream_payments_manual"
  REDIS_URL: "redis://manual-redis:6379"
  RABBITMQ_URL: "amqp://manual-rabbitmq:5672"
  USER_SERVICE_URL: "http://manual-user-service:3001"
  LOG_LEVEL: "debug"
