apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
data:
  PORT: "3004"
  NODE_ENV: "manual"
  ELASTICSEARCH_URL: "http://manual-eswrapper:9200"
  REDIS_URL: "redis://manual-redis:6379"
  CATALOG_SERVICE_URL: "http://manual-catalog-service:3002"
  LOG_LEVEL: "debug"
