apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  PORT: "3001"
  NODE_ENV: "manual"
  MONGODB_URI: "mongodb://manual-mongodb:27017/flixstream_users_manual"
  REDIS_URL: "redis://manual-redis:6379"
  JWT_SECRET: "flixstream-jwt-secret-manual"
  LOG_LEVEL: "debug"
  ALLOWED_ORIGINS: "http://manual-frontend:3000,http://localhost:3000"
