apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-gateway-rollout.yaml
  - api-gateway-preview-service.yaml
  - user-service-rollout.yaml
  - user-service-preview-service.yaml
  - catalog-service-rollout.yaml
  - catalog-service-preview-service.yaml
  - recommendation-service-rollout.yaml
  - recommendation-service-preview-service.yaml
  - search-service-rollout.yaml
  - search-service-preview-service.yaml
  - payment-service-rollout.yaml
  - payment-service-preview-service.yaml
  - frontend-rollout.yaml
  - frontend-preview-service.yaml
